name: Build packages (on push)

# This workflow runs when any of the following occur:
# - Push

on:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  call-build-workflow:
    uses: ./.github/workflows/5_builderpackage_indexer.yml
    secrets: inherit
    with:
      id: ${{ github.ref }}
