name: Build and push Docker image (on push)

# This workflow runs when any of the following occur:
# - Push

on:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  call-docker-workflow:
    uses: ./.github/workflows/5_builderpackage_docker.yml
    secrets: inherit
    with:
      id: ${{ github.ref }}
